using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Meadow.Units.Generators.Templates;

namespace Meadow.Units.Generators;

[Generator]
public class UnitBoilerplateGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // Register a syntax provider to find structs with [GenerateUnitBoilerplate] attribute
        var structDeclarations = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (s, _) => IsStructWithAttribute(s),
                transform: static (ctx, _) => GetStructInfo(ctx))
            .Where(static m => m is not null);

        // Generate code for each struct
        context.RegisterSourceOutput(structDeclarations, static (spc, structInfo) =>
        {
            if (structInfo is null) return;

            var source = GenerateBoilerplateCode(structInfo.Value);
            spc.AddSource($"{structInfo.Value.TypeName}.g.cs", SourceText.From(source, Encoding.UTF8));
        });
    }

    private static bool IsStructWithAttribute(SyntaxNode node)
    {
        // Check if it's a struct with any attributes
        return node is StructDeclarationSyntax structDecl
            && structDecl.AttributeLists.Count > 0;
    }

    private static StructInfo? GetStructInfo(GeneratorSyntaxContext context)
    {
        var structDecl = (StructDeclarationSyntax)context.Node;
        var structSymbol = context.SemanticModel.GetDeclaredSymbol(structDecl);

        if (structSymbol is null) return null;

        // Check if the struct has the [GenerateUnitBoilerplate] attribute
        var attribute = structSymbol.GetAttributes()
            .FirstOrDefault(ad => ad.AttributeClass?.Name == "GenerateUnitBoilerplateAttribute");

        if (attribute is null) return null;

        // Get ValueMemberName from attribute property (default: "Value")
        string valueMemberName = "Value";
        var valueMemberArg = attribute.NamedArguments
            .FirstOrDefault(kvp => kvp.Key == "ValueMemberName");

        if (valueMemberArg.Value.Value is string customName)
        {
            valueMemberName = customName;
        }

        return new StructInfo(
            typeName: structSymbol.Name,
            @namespace: structSymbol.ContainingNamespace.ToDisplayString(),
            valueMemberName: valueMemberName);
    }

    private static string GenerateBoilerplateCode(StructInfo info)
    {
        var sb = new StringBuilder();

        // File header
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using System.Diagnostics.Contracts;");
        sb.AppendLine();
        sb.AppendLine($"namespace {info.Namespace};");
        sb.AppendLine();

        // Begin partial struct
        sb.AppendLine($"public partial struct {info.TypeName}");
        sb.AppendLine("{");

        // Generate each section
        sb.AppendLine(ComparisonOperatorsTemplate.Generate(info.TypeName, info.ValueMemberName));
        sb.AppendLine();

        sb.AppendLine(EqualityMethodsTemplate.Generate(info.TypeName, info.ValueMemberName));
        sb.AppendLine();

        sb.AppendLine(MathOperatorsTemplate.Generate(info.TypeName, info.ValueMemberName));
        sb.AppendLine();

        sb.AppendLine(IComparableDoubleTemplate.Generate(info.TypeName, info.ValueMemberName));
        sb.AppendLine();

        sb.AppendLine(IConvertibleTemplate.Generate(info.TypeName, info.ValueMemberName));

        // End partial struct
        sb.AppendLine("}");

        return sb.ToString();
    }

    private readonly struct StructInfo
    {
        public StructInfo(string typeName, string @namespace, string valueMemberName)
        {
            TypeName = typeName;
            Namespace = @namespace;
            ValueMemberName = valueMemberName;
        }

        public string TypeName { get; }
        public string Namespace { get; }
        public string ValueMemberName { get; }
    }
}
