<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <OutputType>Library</OutputType>
    <AssemblyName>Serialization.System.Text</AssemblyName>
    <Company>Wilderness Labs, Inc</Company>
    <PackageProjectUrl>http://developer.wildernesslabs.co/Meadow/</PackageProjectUrl>
    <PackageId>Meadow.Units.Serialization.System.Text</PackageId>
    <PackageIcon>icon.png</PackageIcon>
    <RepositoryUrl>https://github.com/WildernessLabs/Meadow.Units</RepositoryUrl>
    <PackageTags>Meadow</PackageTags>
    <Version>2.0.0</Version>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <RootNamespace>Meadow.Units.Serialization</RootNamespace>
    <Nullable>enable</Nullable>
    <LangVersion>10</LangVersion>
    <Description>Meadow Units Serialization Library for System.Text.Json</Description>
    <Authors>Wilderness Labs, Inc</Authors>
    <PackageLicenseExpression>Apache-2.0</PackageLicenseExpression>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <LangVersion>latest</LangVersion>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <NoWarn>CS8597;CS8600;CS8601;CS8602;CS8603;CS8604;CS8605;CS8612;CS8618;CS8619;CS8622;CS8714;CS8765;CS8767</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\..\icon.png" Pack="true" PackagePath="" />
  </ItemGroup>
  
  <ItemGroup>
    <ProjectReference Include="..\Meadow.Units\Meadow.Units.csproj" />
  </ItemGroup>

</Project>
