name: Develop Build

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [ develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout Meadow.Units
      uses: actions/checkout@v3
      with:
        ref: develop

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.0.x

    - name: Build
      run: dotnet build -c Release Source/Meadow.Units/Meadow.Units.sln
