<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>

    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
    <PackageReference Include="coverlet.collector" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\Meadow.Foundation\Source\Meadow.Foundation.Libraries_and_Frameworks\Serialization.MicroJson\Driver\Serialization.MicroJson.csproj" />
    <ProjectReference Include="..\Meadow.Units.Serialization.MicroJson\Meadow.Units.Serialization.MicroJson.csproj" />
    <ProjectReference Include="..\Meadow.Units.Serialization.System.Text\Meadow.Units.Serialization.System.Text.csproj" />
    <ProjectReference Include="..\Meadow.Units\Meadow.Units.csproj" />
  </ItemGroup>
</Project>
